# Generated by Django 3.0.6 on 2020-07-29 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_date', models.DateTimeField(default=datetime.datetime(2020, 7, 29, 11, 40, 39, 636201))),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_date', models.DateTimeField(default=datetime.datetime(2020, 7, 29, 11, 40, 39, 635200))),
                ('topic', models.TextField()),
                ('your_take', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_dislikes', models.IntegerField(default=0)),
                ('comment_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment', to='qaportal.Comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaportal.Topics'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_asked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
